### ISSUE TITLE
`data-frame` should work with lists and vectors?

### ISSUE THREAD

**Issue by ezmiller** [alanmarazzi/panthera#9]
I noticed when playing around with the `data-frame` function that the following works where the input to data frame is a vector of maps:
```clj
(data-frame (mapv #(zipmap [:a :b] %) (partition 2 (range 4))))
;;    a  b
;; 0  0  1
;; 1  2  3
```
But where the input is a list things seem to breakdown:
```clj
(data-frame (map #(zipmap [:a :b] %) (partition 2 (range 4))))
;; getting a
;; getting b
;; getting a
;; getting b
;;       a     b
;; 0  None  None
;; 1  None  None
```
Off hand it seems to me that both should work.

**Comment by alanmarazzi** [comment]
I here ya, not a panthera issue, but a libpython-clj one, referred [here](https://github.com/clj-python/libpython-clj/issues/34).

So, yeah, if you take an older version of libpython-clj that code works, with more recent versions it doesn't.
